/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const getActiveHead: typeof import('unhead')['getActiveHead']
  const withHead: typeof import('unhead')['useHead']
  const withHeadSafe: typeof import('unhead')['useHeadSafe']
  const withSeoMeta: typeof import('unhead')['useSeoMeta']
}
